### ISSUE TITLE
Hangup on opening any of the questmenus in the community center

### ISSUE THREAD

**Issue by stop5** [spacechase0/BiggerBackpack#8]
Steps to reproduces:
1. starting an game where at least one of the golden scrolls is unfulfilled, opening the scoll of the rat problem counts
2. go to the community center
3. open any scroll
4. the menu isn't opened, no player related animation is played anymore and the player is impossible to leave the center (including totems).
The juminos are animated as usual, but the events for completing an bundle are not displayed.

i uploaded the log here: https://smapi.io/log/15ebdc6c107041e88d99b2e81ffe82b3
im reporting it here because i think the following line of the log indicates it:
```﻿at StardewValley.Menus.JunimoNoteMenu.setUpMenu_PatchedBy<spacechase0.BiggerBackpack>(JunimoNoteMenu this, Int32 whichArea, Dictionary`2 bundlesComplete)```

**Comment by bcmpinc** [comment]
Can you try it without the mod installed and see if the problem disappears?
